### ISSUE TITLE
Cannot read property 'error' of null on bodyObj.error

### ISSUE THREAD

**Issue by polyclick** [tylerfilla/node-poloniex-unofficial#16]
Hi!

I found a bug! :D

```
.../src/node_modules/poloniex-unofficial/lib/api/trading.js:89
            if (bodyObj.error) {
                       ^

TypeError: Cannot read property 'error' of null
    at Request._callback (/Users/polyclick/Repos/polyclick/filthy-rich/src/node_modules/poloniex-unofficial/lib/api/trading.js:89:24)
    at Request.self.callback (/Users/polyclick/Repos/polyclick/filthy-rich/src/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/polyclick/Repos/polyclick/filthy-rich/src/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/polyclick/Repos/polyclick/filthy-rich/src/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Probably doing a check if `bodyObj` is null would be enough. I wish I knew what happend there in detail but I didn't have my debug proxy open so I can't see what Poloniex is retuning and wether this should be handled in an other way.

**Comment by polyclick** [comment]
I've been debugging a bit more, seems like a problem from the poloniex side. Push api isn't working anymore now. So I guess their whole api is crashing.

I've been logging the content of `body` and `bodyObj`, both contain `null`. Maybe adding an extra if-statement and returning an error is enough in this situation.

**Comment by polyclick** [comment]
Ok, I've got an official confirmation that the Push API is offline. Nothing wrong with the lib then ;) Except for causing a crash of course :p

**Comment by tylerfilla** [comment]
Hi, everything seems to be working now.

I'm assuming you're using the latest release (version 1.1.1).

I am curious about the exact data returned by Poloniex that tripped up the library, as this is a previously unknown failure mode. According to their docs, we should expect their APIs to return a JSON object or die trying. The request obviously went through without a hitch, and a syntax error was not thrown by `JSON.parse()` a few lines previously, so we can assume that valid JSON was provided, yet the parsed value (`bodyObj`) was still null. AFAIK the only way for this to happen is for Poloniex to literally return the word `null`. Even an empty response would have caused a syntax error. Sounds like they have a null check to add ;)

```
All responses from the trading API are in JSON format. In the event of an error, the response will always be of the following format:

{"error":"<error message>"}
```

Since this is not documented, I think it's best to chalk this up as a one-time issue. I've made a new label for this type of problem.

Thanks for the report!

**Comment by tylerfilla** [comment]
Whoops, looks like I accidentally closed the issue with that comment. Please let me know if it should be reopened.

**Comment by polyclick** [comment]
Alright, I got the same issue again today. Looking into it right now. Trying to figure out what Poloniex is returning, but ssl is making it hard for me to see the response. Any hints?

**Comment by tylerfilla** [comment]
I hate to be that "works on my machine" guy, but I'm at a loss here.

I'm just going to run through my logic.

1) Error message is "Cannot read property 'error' of null"
2) `bodyObj` is null
2.5) `bodyObj` is the value returned by `JSON.parse()`
3) Therefore, `JSON.parse()` is returning null
4) I tested out the behavior of various `JSON.parse` inputs on node v4.5.0

``` js
JSON.parse(); // SyntaxError (stringified to "undefined" and choked on the 'u')
JSON.parse(undefined); // SyntaxError (same as above)
JSON.parse({}); // SyntaxError (stringified {} to "[object Object]" and stopped at 'o')
JSON.parse(""); // SyntaxError: Unexpected end of input

// We have our two possibilities
JSON.parse(null);
JSON.parse("null");
```

I previously didn't consider the fact that a raw `null` input will be converted to `"null"` and similarly parsed. Makes a bit more sense. So, the input to `JSON.parse()` must be one of those.
5) `body` is either null or "null"
6) To get to this point, each of `!error`, `response`, and `response.statusCode == 200` must be truthy
7) That last one not yielding a TypeError means the `response` object is valid and the request was successful (as far as the request lib is concerned)

I'm not about to dig into request to see how `body` can be null or "null", yet the request still be successful. I'm willing to assume request is in the right here.

This issue is intermittent. There was no recent change in this library or its dependencies. That indicates to me that Poloniex is triggering the issue. Now, as for who isn't holding up their end of the API contract, that beats me!

**Comment by polyclick** [comment]
@tylerfilla I totally understand man ;) no hard feelings.
I'm willing to help with this issue, currently I've added some extra logging to your programming code to see what the hell is going on :D

Up till now it's just a matter of waiting till the error occurs again.

Will keep you posted.
